name: 'Close problematic stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-issue-label: "A: Won't fix"
          exempt-issue-labels: 'A: By design,A: In progress'
          only-labels: 'A: Problematic'
          days-before-issue-stale: 30
          days-before-issue-close: 5
          remove-issue-stale-when-updated: true
